
version: "3.7"

services:
  nginx:
    image: macbre/nginx-http3:latest
    container_name: nginx-public
    restart: unless-stopped
    ports:
      - 80:80/tcp"
      - 444:443/tcp"
      - 444:443/udp"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - sockets:/tmp/sockets

volumes:
  sockets:
